name: core
description: Core
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.17.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  data:
    path: ../data
  domain:
    path: ../domain
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  get_it: 7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
