name: main
description: Main feature
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.17.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  core:
    path: ../../core
  domain:
    path: ../../domain
  core_ui:
    path: ../../core_ui
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
